# Generated by Django 4.1.2 on 2022-12-15 14:09

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_author_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 14, 9, 9, 704602, tzinfo=datetime.timezone.utc)),
        ),
    ]
