# Generated by Django 4.1.2 on 2022-11-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_country_genre_author_birthday_author_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
