# Generated by Django 4.1.2 on 2022-11-24 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 14, 58, 23, 979119, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('cat', models.ManyToManyField(related_name='category', to='blog.category')),
            ],
        ),
    ]
