# Generated by Django 4.1.2 on 2022-11-30 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_author_birthday_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 11, 30, 13, 46, 39, 752609, tzinfo=datetime.timezone.utc)),
        ),
    ]
